### ISSUE TITLE
include something like vault, but with the ability to register new handlers at runtime so that new handlers can be added without updating vult

### ISSUE THREAD

**Issue by MiniDigger** [Proximyst/SpigotVult#46]

**Comment by ysl3000** [comment]
Like an interface? That money plugins have to implement to support moneytransfer.

**Comment by MiniDigger** [comment]
yes.
vaults api is generally as good example: https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/Economy.java
the problem with vault is, that all providers are hardcoded into the plugin: https://github.com/MilkBowl/Vault/tree/master/src/net/milkbowl/vault/economy/plugins
the goal should be to provide something like vault (or even just implement that api) and make those hooks available to plugins so that they can hook themselves: https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/Vault.java#L244

**Comment by ysl3000** [comment]
Like VultVaulAPI.registerHook(nameofyourhook, yourhook);

How should the API act? Execute class of last registered economy plugin? Or how would you check that not more than one economy plugin is usable? Disable plugin which want to register when a hook already registered from another plugin.

**Comment by ysl3000** [comment]
https://github.com/ysl3000/SpigotVult/tree/master/Spigot-API/src/main/java/org/bukkit/economy

https://github.com/ysl3000/SpigotVult/blob/master/Spigot-API/src/main/java/org/bukkit/Bukkit.java#L115-L122

https://github.com/ysl3000/SpigotVult/blob/master/Spigot-API/src/main/java/org/bukkit/Server.java#L936-L940

Test:
https://github.com/ysl3000/SpigotVult/tree/master/Spigot-API/src/test/java/org/bukkit/economy


Now we need a regulation how to react if a second economy plugin want to register its Economy.
